[menu]
executable = 'fuzzel'
args = [
    '--dmenu',
     '--prompt=ğŸªŸâ¯ ',
     '--width=100',
     '--font=Hack Nerd Font Mono:style=Bold:size=18',
     '--line-height=28',
]

[format]
window_format = "{app_name:{:<11.11}} â€œ{title:{:<60.60}...}â€ {id:{:<3.3}} on {workspace_name:{:<13.13}}\u0000icon\u001f{app_icon}"
indent = '    '
